name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (You can specify the Node.js version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'

      # Step 3: Cache Yarn dependencies
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn-cache
            my-app/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('my-app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
                    
      # Step 4: Enable Docker BuildKit and Build Docker image
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build --cache-from=type=gha --cache-to=type=gha,mode=max -t my-app:latest .